[project]
name = "threatline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bhavya Bharadwaj", email = "188005861+BBcommits@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.22.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
threatline = "threatline:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
